version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      production-minor-patch:
        dependency-type: production
        update-types: [minor, patch]
      development-minor-patch:
        dependency-type: development
        update-types: [minor, patch]
  - package-ecosystem: npm
    directory: "/mcp"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      production-minor-patch:
        dependency-type: production
        update-types: [minor, patch]
      development-minor-patch:
        dependency-type: development
        update-types: [minor, patch]
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      codeql:
        patterns: ["github/codeql-action/*"]
        update-types: [major, minor, patch]
      actions-minor-patch:
        patterns: ["actions/*"]
        update-types: [minor, patch]
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
